### ISSUE TITLE
does cppcheck work for source files in ftp?

### ISSUE THREAD

**Issue by pirDOL** [SublimeLinter/SublimeLinter-cppcheck#11]
I use samba ftp service to mapping a remote linux directory to windows. Then I open the net-mapped directory in windows using sublime text 3. But it seems that sublimelinter & sublimelinter-cppcheck does not work.

If I open a cpp source stored in windows, sublimelinter & sublimelinter-cppcheck works well.

does cppcheck work for source files in ftp?

**Comment by braver** [comment]
This linter only works on files on disk. I doubt it will work well in your particular setup, so if you say it doesn't work, then it doesn't work..
