### ISSUE TITLE
CppCheck refuses to lint .h as C++ files

### ISSUE THREAD

**Issue by Gpinchon** [SublimeLinter/SublimeLinter-cppcheck#22]
#### Issue :
  - CppCheck won't lint .h files as C++ files even though syntax is set to C++ in bottom right

#### Steps to reproduce :
  - Open a C++ header with .h file extension

#### Error Message :
  - Code 'namespaceNameSpace{' is invalid C code. Use --std or --language to configure the language.

#### System Information :
  - Sublime Text Build 3207
  - CppCheck Version 1.88 via MingW64
  - Windows 7 Ultimate

**Comment by kaste** [comment]
Have you tried setting std or language? The plugin doesn't do it atm.

**Comment by Gpinchon** [comment]
The issue is that I don't want CppCheck to lint every .h as C++
It would be nice to have the ability to tell it how to lint a file via Sublime's syntax chooser.
Maybe I am mistaken, but it seems like SublimeLinter allows linters to use this feature ?

**Comment by kaste** [comment]
Ah, yes sure. The clang plugin does that. Look here https://github.com/SublimeLinter/SublimeLinter-clang/blob/master/linter.py how it is done. 

We would welcome such a PR. (I did this for clang.)

**Comment by Gpinchon** [comment]
I will try and check that out if I have time and do a PR.
