### ISSUE TITLE
cppcheck is exectued but errors are not marked 

### ISSUE THREAD

**Issue by fmqeisfeld** [SublimeLinter/SublimeLinter-cppcheck#23]
Not sure what I'm doing wrong.
My config looks like this:

```
{
    // Set to true to print extra information in the console.
    "debug": true,
    "lint_mode": "save",
    "linters": {
        "cppcheck": {
            "@disable": false,
            "args": [],
            "enable": "style",
            "excludes": [],
            "std": "c++11",
            "syntax_map": {
                "c++11": "c++"
            }
        }
    }
}
```
The test-file (from the docs):

#include <iostream>

using namespace std;

```
int main()
{
    cout << "it works" << endl;

    return 0;

```

After saving, the output is printed to the console:

```
  /home/zac  (working dir)
  $ /usr/bin/cppcheck --template={file}:{line}:{column}:{severity}:{id}:{message} --inline-suppr --quiet --std=c++11 --enable=style /home/zac/myerror.cpp

SublimeLinter: #3 linter.py:1202      cppcheck: output:
  /home/zac/myerror.cpp:6:{column}:error:syntaxError:Invalid number of character '{' when no macros are defined.
SublimeLinter: #3 linter.py:1254      cppcheck: No match for line: '/home/zac/myerror.cpp:6:{column}:error:syntaxError:Invalid number of character '{' when no macros are defined.'
SublimeLinter: sublime_linter.py:575  Linting 'myerror.cpp' took 0.02s

```

cppcheck seems to work. 
However, there are no hints or marks inside the editor. What am I missing?

**Comment by kaste** [comment]
You're not doing anything wrong here, but your `cppcheck` does not provide `{column}` information.  You see that via the `--template` flag we explicitly ask for the column, but the output produced literally returns `file:6:{column}:...` which doesn't match our expectation.  (The next line we log is "No match for ...".)

I'm not an expert for `cppcheck` but maybe you can just use a newer one?

**Comment by frankzack** [comment]
> You're not doing anything wrong here, but your `cppcheck` does not provide `{column}` information. You see that via the `--template` flag we explicitly ask for the column, but the output produced literally returns `file:6:{column}:...` which doesn't match our expectation. (The next line we log is "No match for ...".)
> 
> I'm not an expert for `cppcheck` but maybe you can just use a newer one?

Thank you kaste. Updating to the recent version 1.90 indeed solved the problem.
