### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by plasmaphase** [SublimeLinter/SublimeLinter-cppcheck#6]
For some reason I am unable to install via package control due to this error:

File "./plistlib.py", line 378, in parse
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 23, column 0

Any suggestions?

**Comment by plasmaphase** [comment]
Is this not available for windows?

xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 23, column 0
Package Control: The package "SublimeLinter-cppcheck" is not available on this platform.

**Comment by NotSqrt** [comment]
Just tried on Windows XP, it works like a charm ..

**Comment by plasmaphase** [comment]
Strange.  I uninstalled Sublime Text 3 completely and re-installed, and it worked just fine.  Sorry.
